//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.InvoicePayments = new HashSet<InvoicePayment>();
        }
    
        public int BookingID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public int RoomID { get; set; }

        [Required(ErrorMessage = "*Bạn chưa nhập tên")]
        [StringLength(50, ErrorMessage = "*Tên không vượt quá 50 ký tự")]
        public string CustomerName { get; set; }

        [Required(ErrorMessage = "*Bạn chưa nhập email")]
        [EmailAddress(ErrorMessage = "*Email không hợp lệ")]
        public string Email { get; set; }

        [Required(ErrorMessage = "*Bạn chưa nhập số điện thoại")]
        [MinLength(10,ErrorMessage ="*Số điện thoại tối thiểu 10 số")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "*Bạn chưa nhập số CCCD")]
        [MinLength(12,ErrorMessage = "*Số CCCD tối thiểu 12 số")]
        public string IdentifyNo { get; set; }

        public Nullable<System.DateTime> BookingDate { get; set; }

        [Required(ErrorMessage = "*Hãy chọn ngày check in")]
        public Nullable<System.DateTime> CheckinDate { get; set; }

        [Required(ErrorMessage = "*Hãy chọn ngày check out")]
        public Nullable<System.DateTime> CheckoutDate { get; set; }

        public Nullable<int> Adult { get; set; }
        public Nullable<int> Child { get; set; }
        public string PromotionCode { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePayment> InvoicePayments { get; set; }
        public virtual Service Service { get; set; }
    }
}
