//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int CustomerID { get; set; }

        [Required(ErrorMessage = "Required information field")]
        [StringLength(50, ErrorMessage = "Name don't exceed 50 character")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Required information field")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Required information field")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Required information field")]
        public string IdentifyNumber { get; set; }

        [Required(ErrorMessage = "Required information field")]
        [EmailAddress(ErrorMessage = "Email format is invalid")]
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }

        public string Password { get; set; }
        public string Image { get; set; }
        public Nullable<int> PromotionID { get; set; }
    
        public virtual Promotion Promotion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
