//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product_Color = new HashSet<Product_Color>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Image { get; set; }
        public string ProductCode { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<int> SoldQuantity { get; set; }
        public Nullable<decimal> DiscountPrice { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Color { get; set; }
        public string Style { get; set; }
        public string Material { get; set; }
        public string Feature { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Color> Product_Color { get; set; }
        public virtual Promotion Promotion { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
