//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Promotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotion()
        {
            this.Customers = new HashSet<Customer>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int PromotionID { get; set; }
        public string PromotionName { get; set; }

        [Required(ErrorMessage = "Required information field")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Required information field")]
        public Nullable<System.DateTime> StartDate { get; set; }

        [Required(ErrorMessage = "Required information field")]
        public Nullable<System.DateTime> EndDate { get; set; }

        [Required(ErrorMessage = "Required information field")]
        public string Conditions { get; set; }

        [Required(ErrorMessage = "Required information field")]
        public string PromotionCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
