//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail
    {
        public int ReceiptDetailD { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ReceiptID { get; set; }
        public Nullable<int> ProductColorID { get; set; }
    
        public virtual Product_Color Product_Color { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
