//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HMEntities : DbContext
    {
        public HMEntities()
            : base("name=HMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_Bookings> tb_Bookings { get; set; }
        public virtual DbSet<tb_Customers> tb_Customers { get; set; }
        public virtual DbSet<tb_Employees> tb_Employees { get; set; }
        public virtual DbSet<tb_Invoices> tb_Invoices { get; set; }
        public virtual DbSet<tb_Managers> tb_Managers { get; set; }
        public virtual DbSet<tb_Payments> tb_Payments { get; set; }
        public virtual DbSet<tb_Promotions> tb_Promotions { get; set; }
        public virtual DbSet<tb_Rooms> tb_Rooms { get; set; }
        public virtual DbSet<tb_Searchs> tb_Searchs { get; set; }
        public virtual DbSet<tb_Services> tb_Services { get; set; }
    }
}
