//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Bookings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Bookings()
        {
            this.tb_Invoices = new HashSet<tb_Invoices>();
        }
    
        public int BookingID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> ChekinDate { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
    
        public virtual tb_Customers tb_Customers { get; set; }
        public virtual tb_Rooms tb_Rooms { get; set; }
        public virtual tb_Services tb_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Invoices> tb_Invoices { get; set; }
    }
}
