//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Payments
    {
        public int PaymentID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string PaymentType { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> PromotionID { get; set; }
    
        public virtual tb_Customers tb_Customers { get; set; }
        public virtual tb_Invoices tb_Invoices { get; set; }
        public virtual tb_Promotions tb_Promotions { get; set; }
    }
}
